<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper  <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <ol data-mage-init='{"Winkel_Catalog/js/product-loader":{
          "pager":{
            "wrapperEl":"#pager-wrapper",
            "totalCount":"#num-total-prods",
            "showCount":"#num-shown-prods",
            "shownEl":"#prod-load-status-val",
            "moreButton":"#product-load-trigger"
          }
        }}' class="products product-item-filtered mx-0 list items product-items">
        </ol>
    </div>
    <div class="text-center mb-5" style="display:none" id="pager-wrapper">
      <p>Showing <span id="num-shown-prods"></span> of <span id="num-total-products"></span> Products</p>
      <div id="prod-load-status" style="width: 250px; margin:auto; height: 5px; background: #dddddd">
        <div id="prod-load-status-val" style="width: 0px; height: 5px; transition: all .3s ease-in-out; background: #000"></div>
      </div>
      <a href="#" style="display:none" class="btn btn-secondary main-button text-light my-5" id="product-load-trigger" data-text="<?= __('View More') ?>"><?= __('View More') ?></a>
    </div>
<?php endif; ?>




<script type="text/javascript">
  require(['jquery'], function($){

  })
</script>
